name: "User created from web site"
id: user-created

requirements:
    data:
        - hostname: 'adequancy.com'

stages:
    - lehibou_do_created:
        job: add_reply
        data:
            - api_key: "%reply_do_api_key%"
            - campaign_id: "%campaign_reply_doi%"

